// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/screener-variants/MarketCards.tsx": () => import("../components/mockups/screener-variants/MarketCards.tsx"),
  "./components/mockups/screener-variants/ProTerminal.tsx": () => import("../components/mockups/screener-variants/ProTerminal.tsx"),
  "./components/mockups/screener-variants/SignalFeed.tsx": () => import("../components/mockups/screener-variants/SignalFeed.tsx")
};
